/*
 * Inserts the speakers from 2012
 * Notice that the first attirbute, id, is NULL. This is because it is an auto-increment.
*/
insert into speaker values (NULL, "Ian", "Ratner", 2023, TRUE, TRUE);
insert into speaker values (NULL, "Ram", "Karra", 2023, TRUE, TRUE);
insert into speaker values (NULL,"Deborah","Cliburn",2023, TRUE, TRUE);
insert into speaker values (NULL,"Prashanth","Chakrapani",2023, TRUE, TRUE);
insert into speaker values (NULL,"Scott","Cruze",2023, TRUE, TRUE);
insert into speaker values (NULL,"Mark","Kelly",2023, TRUE, TRUE);
insert into speaker values (NULL,"Jim","Senter",2023, TRUE, TRUE);
insert into speaker values (NULL,"Phil","Spann",2023, TRUE, TRUE);
insert into speaker values (NULL,"Jeffrey","Allen",2023, TRUE, TRUE);
insert into speaker  values (NULL,"Bhaumik","Shah",2023, TRUE, TRUE);
insert into speaker  values (NULL,"Panagiotis","Tzerefos",2023, TRUE, TRUE);
insert into speaker values (NULL,"Ben","Pack",2023, TRUE, TRUE);
insert into speaker values (NULL,"David","Tucker",2023, TRUE, TRUE);
insert into speaker values (NULL,"Matt","Peter",2023, TRUE, TRUE);
insert into speaker values (NULL,"Pedro","Lopez",2023, TRUE, TRUE);
insert into speaker values (NULL,"John","Hills",2023, TRUE, TRUE);
insert into speaker values (NULL,"Bryan","Fails",2023, TRUE, TRUE);
insert into speaker values (NULL,"Glen","Wright",2023, TRUE, TRUE);
insert into speaker values (NULL,"Kevin","Barry",2023, TRUE, TRUE);
insert into speaker values (NULL,"Jeffery","Kissinger",2023, TRUE, TRUE);
insert into speaker values (NULL,"Beth","Jackson",2023, TRUE, TRUE);
insert into speaker values (NULL,"Brian","Hinsley",2023, TRUE, TRUE);
insert into speaker values (NULL,"Drew","Fredrick",2023, TRUE, TRUE);
insert into speaker values (NULL,"Glen","Ireland",2023, TRUE, TRUE);
insert into speaker values (NULL,"Robert","Clarence",2023, TRUE, TRUE);
insert into speaker values (NULL,"Sarah","Cottay",2023, TRUE, TRUE);
insert into speaker values (NULL,"Channing","Dawson",2023, TRUE, TRUE);
insert into speaker values (NULL,"Mike","Campbell",2023, TRUE, TRUE);
insert into speaker values (NULL,"Joshua","Eldridge",2023, TRUE, TRUE);
insert into speaker values (NULL,"Bruce","Parker",2023, TRUE, TRUE);
insert into speaker values (NULL,"Robin","Wilde",2023, TRUE, TRUE);
insert into speaker values (NULL,"Lydia","Cordell",2023, TRUE, TRUE);
insert into speaker values (NULL,"Team","Nirvana",2023, TRUE, TRUE);
insert into speaker values (NULL,"Amy","Thomason",2023, TRUE, TRUE);
insert into speaker values (NULL,"Charles","Lewis",2023, TRUE, TRUE);
insert into speaker values (NULL,"Jonathan","Williams",2023, TRUE, TRUE);
insert into speaker values (NULL,"Scott","Gentry",2023, TRUE, TRUE);
insert into speaker  values (NULL,"Jason","Norton",2023, TRUE, TRUE);
insert into speaker values (NULL,"Michael","Wehrle",2023, TRUE, TRUE);
insert into speaker values (NULL,"Shane","Closser",2023, TRUE, TRUE);
insert into speaker values (NULL,"Selene","Tolbert",2023, TRUE, TRUE);
insert into speaker values (NULL,"Michael","Berger",2023, TRUE, TRUE);
insert into speaker values (NULL,"Kamlesh","Sharma",2023, TRUE, TRUE);
insert into speaker values (NULL,"Kabita","Nayak",2023, TRUE, TRUE);
insert into speaker values (NULL,"Herb","Himes",2023, TRUE, TRUE);
insert into speaker values (NULL,"Stefanie","Edinger",2023, TRUE, TRUE);
insert into speaker values (NULL, "Phil", "Cornell", 2023, TRUE, TRUE);
insert into speaker values (NULL,"Allen", "Shacklock", 2023, TRUE, TRUE);