/*
Inserts the speakers from 2012
*/
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (0, "Ian", "Ratner", 2023);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (1, "Ram", "Karra", 2023);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (2,"Deborah","Cliburn",2023);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (3,"Prashanth","Chakrapani",2023);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (4,"Scott","Cruze",2023);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (5,"Mark","Kelly",2023);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (6,"Jim","Senter",2023);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (7,"Phil","Spann",2023);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (8,"Jeffrey","Allen",2023);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (9,"Bhaumik","Shah",2023);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (10,"Panagiotis","Tzerefos",2023);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (11,"Ben","Pack",2023);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (12,"David","Tucker",2023);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (13,"Matt","Peter",2023);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (14,"Pedro","Lopez",2023);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (15,"John","Hills",2023);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (16,"Bryan","Fails",2023);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (17,"Glen","Wright",2023);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (18,"Kevin","Barry",2023);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (19,"Jeffery","Kissinger",2023);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (20,"Beth","Jackson",2023);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (21,"Brian","Hinsley",2023);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (22,"Drew","Fredrick",2023);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (23,"Glen","Ireland",2023);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (24,"Robert","Clarence",2023);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (25,"Sarah","Cottay",2023);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (26,"Channing","Dawson",2023);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (27,"Mike","Campbell",2023);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (28,"Joshua","Eldridge",2023);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (29,"Bruce","Parker",2023);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (30,"Robin","Wilde",2023);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (31,"Lydia","Cordell",2023);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (32,"Team","Nirvana",2023);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (33,"Amy","Thomason",2023);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (34,"Charles","Lewis",2023);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (35,"Jonathan","Williams",2023);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (36,"Scott","Gentry",2023);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (37,"Jason","Norton",2023);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (38,"Michael","Wehrle",2023);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (39,"Shane","Closser",2023);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (40,"Selene","Tolbert",2023);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (41,"Michael","Berger",2023);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (42,"Kamlesh","Sharma",2023);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (43,"Kabita","Nayak",2023);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (44,"Herb","Himes",2023);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (45,"Stefanie","Edinger",2023);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (46,
"Phil", "Cornell", 2023);
insert into speaker (speaker_id, speaker_first, speaker_last, suggested_by) values (47,"Allen", "Shacklock", 2023);