/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.35
 * Generated at: 2013-02-22 07:56:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.SQLException;
import java.sql.DriverManager;
import java.util.Properties;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import com.scripps.growler.DataConnection;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      com.scripps.growler.DataConnection dataConnection = null;
      synchronized (application) {
        dataConnection = (com.scripps.growler.DataConnection) _jspx_page_context.getAttribute("dataConnection", javax.servlet.jsp.PageContext.APPLICATION_SCOPE);
        if (dataConnection == null){
          dataConnection = new com.scripps.growler.DataConnection();
          _jspx_page_context.setAttribute("dataConnection", dataConnection, javax.servlet.jsp.PageContext.APPLICATION_SCOPE);
        }
      }
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspect(_jspx_page_context.findAttribute("dataConnection"), request);
      out.write("\n");
      out.write("\n");
      out.write("<!doctype html>\n");
      out.write("<!--[if lt IE 7]> <html class=\"no-js lt-ie9 lt-ie8 lt-ie7\" lang=\"en\"> <![endif]-->\n");
      out.write("<!--[if IE 7]>    <html class=\"no-js lt-ie9 lt-ie8\" lang=\"en\"> <![endif]-->\n");
      out.write("<!--[if IE 8]>    <html class=\"no-js lt-ie9\" lang=\"en\"> <![endif]-->\n");
      out.write("<!--[if gt IE 8]><!--> <html class=\"no-js\" lang=\"en\"> <!--<![endif]-->\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"utf-8\" />\n");
      out.write("  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\" />\n");
      out.write("  <title>Growler Project</title><!-- Title -->\n");
      out.write("  <meta name=\"description\" content=\"Growler Project Tentative Layout\" /><!-- Description -->\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/bootstrap/bootstrap.1.2.0.css\" /><!--Using bootstrap 1.2.0-->\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/bootstrap/responsive.1.2.0.css\" /><!--Basic responsive layout enabled-->\n");
      out.write("\t<link rel=\"stylesheet\" href=\"draganddrop.css\" /><!--Drag and drop style-->\n");
      out.write("  <script src=\"js/libs/modernizr.2.6.2.custom.min.js\"></script><!--Modernizer-->\n");
      out.write("</head>\n");
      out.write("<body id=\"growler1\">\n");
      out.write("    \n");
      out.write("    \n");
      out.write("    \n");
      out.write("\n");
      out.write("    \n");
      out.write("  <header class=\"pageHeader\">\n");
      out.write("    <div class=\"pageHeader-portal\">\n");
      out.write("      <div class=\"pageHeader-logo\">\n");
      out.write("        <a href=\"/\"></a>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </header><!-- /.pageHeader -->\n");
      out.write("\t<nav class=\"globalNavigation\">\n");
      out.write("        <ul>\n");
      out.write("\t\t\t\t\t\t<li class=\"selected\"><a href=\"../index.html\">Themes</a></li>\n");
      out.write("            <li><a href=\"themeentry.html\">Suggest a Theme</a></li>\n");
      out.write("            <li><a href=\"\">Speakers</a></li>\n");
      out.write("            <li><a href=\"\">Suggest a Speaker</a></li>\n");
      out.write("            <li><a href=\"\">Help</a></li>\n");
      out.write("        </ul>\n");
      out.write("  </nav><!-- /.globalNavigation -->\n");
      out.write("  <div class=\"container-fixed\">\n");
      out.write("\t\t<div class=\"content\">\n");
      out.write("\t\t\t<!-- Begin Content -->\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t<div class=\"span12\">\n");
      out.write("\t\t\t\t\t<img class=\"logo\" src=\"Techtoberfest2013.png\" alt=\"Techtoberfest 2013\"/>  <!-- Techtoberfest logo-->\n");
      out.write("\t\t\t\t\t<h1 class = \"bordered\">Themes</h1>\n");
      out.write("\t\t\t\t\t</br>\n");
      out.write("\t\t\t\t\t</br>\n");
      out.write("                                        ");
      out.write("\n");
      out.write("                                        ");
 ResultSet results = dataConnection.selectThemes();
                                         
                                            while (results.next()) {
                                        
      out.write(" <p> ");
 out.println(results.getString("name")); 
      out.write("</p>\n");
      out.write("    ");
 }
      out.write("\n");
      out.write("                                        ");
 Connection connection = dataConnection.sendConnection();
                                        Statement other = connection.createStatement();
                                        ResultSet descriptions = other.executeQuery("select description from theme");
                                        while (descriptions.next()) {
                                        
      out.write(" <p>");
out.println(descriptions.getString("description")); 
      out.write("</p>\n");
      out.write("                                        ");
 } 
      out.write("\n");
      out.write("                                        \n");
      out.write("                                            \n");
      out.write("                                           \n");
      out.write("                                        \n");
      out.write("\t\t\t\t\t\t\t<h3>Drag and drop themes to rank them!<h3>\n");
      out.write("\t\t\t\t\t\t\t<h5>**Only the top ten themes will be ranked</h5>\n");
      out.write("\t\t\t\t\t</br>\n");
      out.write("\t\t\t\t\t<div id=\"tabs-1\">\n");
      out.write("\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t<div class=\"span3\">\n");
      out.write("\t\t\t\t\t\t<p></p>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"span1\">\n");
      out.write("\t\t\t\t\t\t\t</br> \n");
      out.write("\t\t\t\t\t\t\t<div>1</div>\n");
      out.write("\t\t\t\t\t\t\t</br>\n");
      out.write("\t\t\t\t\t\t\t</br>\n");
      out.write("\t\t\t\t\t\t\t</br>\n");
      out.write("\t\t\t\t\t\t\t<div>2</div>\n");
      out.write("\t\t\t\t\t\t\t</br>\n");
      out.write("\t\t\t\t\t\t\t</br>\n");
      out.write("\t\t\t\t\t\t\t</br>\n");
      out.write("\t\t\t\t\t\t\t<div>3</div>\n");
      out.write("\t\t\t\t\t\t\t</br>\n");
      out.write("\t\t\t\t\t\t\t</br>\n");
      out.write("\t\t\t\t\t\t\t</br>\n");
      out.write("\t\t\t\t\t\t\t<div>4</div>\n");
      out.write("\t\t\t\t\t\t\t</br>\n");
      out.write("\t\t\t\t\t\t\t</br>\n");
      out.write("\t\t\t\t\t\t\t</br>\n");
      out.write("\t\t\t\t\t\t\t<div>5</div>\n");
      out.write("\t\t\t\t\t\t\t</br>\n");
      out.write("\t\t\t\t\t\t\t</br>\n");
      out.write("\t\t\t\t\t\t\t</br>\n");
      out.write("\t\t\t\t\t\t\t<div>6</div>\n");
      out.write("\t\t\t\t\t\t\t</br>\n");
      out.write("\t\t\t\t\t\t\t</br>\n");
      out.write("\t\t\t\t\t\t\t</br>\n");
      out.write("\t\t\t\t\t\t\t<div>7</div>\n");
      out.write("\t\t\t\t\t\t\t</br>\n");
      out.write("\t\t\t\t\t\t\t</br>\n");
      out.write("\t\t\t\t\t\t\t</br>\n");
      out.write("\t\t\t\t\t\t\t<div>8</div>\n");
      out.write("\t\t\t\t\t\t\t</br>\n");
      out.write("\t\t\t\t\t\t\t</br>\n");
      out.write("\t\t\t\t\t\t\t</br>\n");
      out.write("\t\t\t\t\t\t\t<div>9</div>\n");
      out.write("\t\t\t\t\t\t\t</br>\n");
      out.write("\t\t\t\t\t\t\t</br>\n");
      out.write("\t\t\t\t\t\t\t<div>10</div>\n");
      out.write("\t\t\t\t\t\t\t</br>\n");
      out.write("\t\t\t\t\t\t\t</br>\n");
      out.write("\t\t\t\t\t\t\t<div>11</div>\n");
      out.write("\t\t\t\t\t\t\t</br>\n");
      out.write("\t\t\t\t\t\t\t</br>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"span2\">\n");
      out.write("\t\t\t\t\t<section>\n");
      out.write("\t\t\t\t\t\t<ul class=\"sortable grid\">\n");
      out.write("\t\t\t\t\t\t\t<li>Cloud Computing</li>\n");
      out.write("\t\t\t\t\t\t\t<li>Development Frameworks</li>\n");
      out.write("\t\t\t\t\t\t\t<li>Software Process / Lifecycle</li>\n");
      out.write("\t\t\t\t\t\t\t<li>Mobility</li>\n");
      out.write("\t\t\t\t\t\t\t<li>Social and Collaboration</li>\n");
      out.write("\t\t\t\t\t\t\t<li>Show & Tell</li>\n");
      out.write("\t\t\t\t\t\t\t<li>Cross Platform Programming</li>\n");
      out.write("\t\t\t\t\t\t\t<li>Happy Shining People</li>\n");
      out.write("\t\t\t\t\t\t\t<li>Holding Hands</li>\n");
      out.write("\t\t\t\t\t\t\t<li>It's the end of the world</li>\n");
      out.write("\t\t\t\t\t\t\t<li>and I feel fine...</li>\n");
      out.write("\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t</section>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"span7\">\n");
      out.write("\t\t\t\t\t<p></p>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<!--\n");
      out.write("\t\t\t\t\t<div id=\"tabs-1\">\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"span6\">\n");
      out.write("\t\t\t\t\t\t\t\t<table class=\"table table-alternatingRow table-border table-columnBorder\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<thead>\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Ranking</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Suggested Themes</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t</thead>\n");
      out.write("\t\t\t\t\t\t\t\t\t<tbody>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>1</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div id=\"div1\" ondrop=\"drop(event)\" ondragover=\"allowDrop(event)\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<p id=\"drag1\" draggable=\"true\" ondragstart=\"drag(event)\">Cloud Computing</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>2</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div id=\"div1\" ondrop=\"drop(event)\" ondragover=\"allowDrop(event)\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<p id=\"drag1\" draggable=\"true\" ondragstart=\"drag(event)\">Development Frameworks</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>3</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td id=\"drag1\">Software Process / Lifecycle</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>4</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td id=\"drag1\">Mobility</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>5</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td id=\"drag1\">Social and Collaboration</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>6</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td id=\"drag1\">Show & Tell</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t</tbody>\n");
      out.write("\t\t\t\t\t\t\t\t</table>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>-->\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!-- End Content -->\n");
      out.write("\t\t</div>\t\n");
      out.write("  </div>\n");
      out.write("\t<div class=\"row\">\n");
      out.write("\t\t<div class=\"span8\">\n");
      out.write("\t\t\t<p></p>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"span2\">\n");
      out.write("\t\t\t<input type=\"submit\" value=\"Submit Ratings\" class=\"button button-primary\"/>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\t\n");
      out.write("\n");
      out.write("  <footer class=\"pageFooter\">\n");
      out.write("    <hr />\n");
      out.write("    <p>Scripps Networks Interactive Bootstrap version 1.2.0.<!-- Application name --></p>\n");
      out.write("    <p>Copyright &copy; 2013 Scripps Networks Interactive</p>\n");
      out.write("  </footer><!-- /.pageFooter -->\n");
      out.write("\t\n");
      out.write("\t<script src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js\"></script>\n");
      out.write("\t<script src=\"jquery.sortable.js\"></script><!--Drag and drop for non-iOS-->\n");
      out.write("\t<script src=\"js/libs/jquery-1.8.3.min.js\" type=\"text/javascript\"></script>\n");
      out.write("\t<script src=\"js/libs/jquery-ui-1.9.2.custom.min.js\" type=\"text/javascript\"></script>\n");
      out.write("\t<script src=\"js/libs/jquery.dataTables.1.9.3.min.js\" type=\"text/javascript\"></script>\n");
      out.write("\t<script src=\"js/libs/sniui.dataTables.1.0.0.min.js\" type=\"text/javascript\"></script>\n");
      out.write("\t\n");
      out.write("\t<!--drag and drop extra script-->\n");
      out.write("\t<script>\n");
      out.write("\t$(function() {\n");
      out.write("\t$('.sortable').sortable();\n");
      out.write("\t$('.handles').sortable({\n");
      out.write("\thandle: 'span'\n");
      out.write("\t});\n");
      out.write("\t$('.connected').sortable({\n");
      out.write("\tconnectWith: '.connected'\n");
      out.write("\t});\n");
      out.write("\t$('.exclude').sortable({\n");
      out.write("\titems: ':not(.disabled)'\n");
      out.write("\t});\n");
      out.write("\t});\n");
      out.write("\t</script>\n");
      out.write("\t<script type=\"text/javascript\">\n");
      out.write("\t\t\t$(function () {\n");
      out.write("\t\t\t\t\t$(\"#tabs\").tabs();\n");
      out.write("\n");
      out.write("\t\t\t\t\t$('#showsTable').dataTable({\n");
      out.write("\t\t\t\t\t\t\t'aoColumns': [\n");
      out.write("\t\t\t\t\t\t\t\t\t{ 'bSortable': false },\n");
      out.write("\t\t\t\t\t\t\t\t\t{ 'bSortable': true },\n");
      out.write("\t\t\t\t\t\t\t\t\t{ 'bSortable': true },\n");
      out.write("\t\t\t\t\t\t\t\t\t{ 'bSortable': true },\n");
      out.write("\t\t\t\t\t\t\t\t\t{ 'bSortable': true },\n");
      out.write("\t\t\t\t\t\t\t\t\t{ 'bSortable': true },\n");
      out.write("\t\t\t\t\t\t\t\t\t{ 'bSortable': true }, \n");
      out.write("\t\t\t\t\t\t\t\t\t{ 'bSortable': true },\n");
      out.write("\t\t\t\t\t\t\t\t\t{ 'bSortable': true },\n");
      out.write("\t\t\t\t\t\t\t\t\t{ 'bSortable': false }    \n");
      out.write("\t\t\t\t\t\t\t],\n");
      out.write("\t\t\t\t\t\t\t'aaSorting': [[1, 'asc']],\n");
      out.write("\t\t\t\t\t\t\t'fnHeaderCallback': Scripps.DataTables.fnHeaderCallback,\n");
      out.write("\t\t\t\t\t\t\t'bFilter': false,\n");
      out.write("\t\t\t\t\t\t\t'bLengthChange': false,\n");
      out.write("\t\t\t\t\t\t\t'sPaginationType': 'scripps'\n");
      out.write("\t\t\t\t\t});\n");
      out.write("\n");
      out.write("\t\t\t\t\t$(\"#assignmentsTabs\").tabs();\n");
      out.write("\n");
      out.write("\t\t\t\t\t$('#assignmentsTable').dataTable({\n");
      out.write("\t\t\t\t\t\t\t'aoColumns': [\n");
      out.write("\t\t\t\t\t\t\t\t\t{ 'bSortable': false },\n");
      out.write("\t\t\t\t\t\t\t\t\t{ 'bSortable': true },\n");
      out.write("\t\t\t\t\t\t\t\t\t{ 'bSortable': true },\n");
      out.write("\t\t\t\t\t\t\t\t\t{ 'bSortable': true },\n");
      out.write("\t\t\t\t\t\t\t\t\t{ 'bSortable': true },\n");
      out.write("\t\t\t\t\t\t\t\t\t{ 'bSortable': true },\n");
      out.write("\t\t\t\t\t\t\t\t\t{ 'bSortable': true },\n");
      out.write("\t\t\t\t\t\t\t\t\t{ 'bSortable': false },\n");
      out.write("\t\t\t\t\t\t\t],\n");
      out.write("\t\t\t\t\t\t\t'aaSorting': [[1, 'asc']],\n");
      out.write("\t\t\t\t\t\t\t'fnHeaderCallback': Scripps.DataTables.fnHeaderCallback,\n");
      out.write("\t\t\t\t\t\t\t'bFilter': false,\n");
      out.write("\t\t\t\t\t\t\t'bLengthChange': false,\n");
      out.write("\t\t\t\t\t\t\t'sPaginationType': 'scripps'\n");
      out.write("\t\t\t\t\t});\n");
      out.write("\t\t\t});\n");
      out.write("\t</script>\n");
      out.write("\t<script type=\"text/javascript\">\n");
      out.write("\t$(function() {\n");
      out.write("    $( \".inlineTabs\" ).tabs();\n");
      out.write("    });\n");
      out.write("\t</script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
